name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup network
        run: docker network create jcnet
      - name: Build the stack
        run: docker-compose build
      - name: Run the stack
        run: docker-compose up       
